// flow-typed signature: c268fa6cb1589b99a1161b6086208bfe
// flow-typed version: <<STUB>>/micro_vgithub:zeit/micro/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'micro'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'micro' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'micro/bin/micro' {
  declare module.exports: any;
}

declare module 'micro/lib/index' {
  declare module.exports: any;
}

declare module 'micro/lib/listening' {
  declare module.exports: any;
}

declare module 'micro/lib/module' {
  declare module.exports: any;
}

declare module 'micro/lib/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'micro/bin/micro.js' {
  declare module.exports: $Exports<'micro/bin/micro'>;
}
declare module 'micro/lib/index.js' {
  declare module.exports: $Exports<'micro/lib/index'>;
}
declare module 'micro/lib/listening.js' {
  declare module.exports: $Exports<'micro/lib/listening'>;
}
declare module 'micro/lib/module.js' {
  declare module.exports: $Exports<'micro/lib/module'>;
}
declare module 'micro/lib/server.js' {
  declare module.exports: $Exports<'micro/lib/server'>;
}
